### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by FoRVaiS** [FoRVaiS/wingman#1]
## April Roadmap

The goal for this month is to build our project infrastructure as well as implement user authentication, enable users to view tweets, and provide a feature for downloading tweet attachments.

|Milestone|Version|Due Date|
|---|---|---|
|1. Project Infrastructure|0.1.0|April 15, 2023|
|2. Sign In and Tweet Scraping|0.2.0|April 20, 2023|
|3. Downloading and Storing Tweet Attachments|0.3.0|April 26, 2023|
|4. Twitter Feed|0.4.0|April 29, 2023|

### v0.1.0 (Milestone 1: Project Infrastructure)
- [ ] Create repos for the scraper, api, and ui
- [ ] Write scripts to propagate checkout, install, qa, and build commands
- [ ] Create a multi-stage dockerfile for launching the entire project in a development container or in a development/production environmment
- [ ] Deploy development MongoDB and Redis instances for development environments
- [ ] Build a VSCode development container
- [ ] Install and configure code quality tools (Jest, Eslint)
- [ ] Install and configure collaboration tools (Commitizen, Changelog)
- [ ] Build a CI/CD pipeline in each submodule to run unit tests using GitHub Actions

### v0.2.0 (Milestone 2: Sign In and Tweet Scraping)
- [ ] Generate and store Twitter session tokens
- [ ] Persist login sessions with node-sessions
- [ ] Scrape tweet bodies and attachments
- [ ] Build UI for signing in and displaying a single tweet
- [ ] Store and cache tweet data

### v0.3.0 (Milestone 3: Downloading and Storing Tweet Attachments)
- [ ] Implement support for HLS streams and conversion to mp4 using FFMPEG
- [ ] Store raw attachments in local file storage or TrueNAS
- [ ] Build a UI for downloading attachments

### v0.4.0 (Milestone 4: Twitter Feed)
- [ ] Scrape tweets from the 'For You' and 'Following' feeds

**Comment by FoRVaiS** [comment]
Closing issue to hide from issue ticker.
